server:
  port: 8763

spring:
  application:
    name: Service-Provider

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    auto-mapping-behavior: full


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
